crud funcional
afar-cmyk/ProyectoBibliotech pull request #76
Opened 2021-10-02 20:42 UTC by jsstiven

este commit contiene lo siguiente

1. lista de manera dinamica y funcional los articulos de la clase item 
2. crea de manera dinamica y funcional los articulos de la clase item 
3. edita de manera dinamica y funcional los articulos de la clase item 
4. elimina de manera dinamica y funcional los articulos de la clase item 
5. se agrego parte de la vista new_item.html a la vista vue item.vue
6. no se realizo un componente de listar articulos debido a la razon de que es necesario tenerlo en una sola clase para asi poder hacer los procesos de editar y eliminar con facilidad y  de manera dinamica 
7. falta hacer la lista en otra vista como newer pero por la entrega se hace este commit de manera que se tenga lo principal que se esta pidiendo esta semana

2021-10-03 17:23 UTC, muakarada approved these changes
Ok, se ve bien el proceso y los cambios.

2021-10-03 22:48 UTC, Jesteban247 approved these changes

2021-10-04 19:17 UTC, jsstiven commented
hola compañeros les pido que no vayan a dar el merge pull que puede que haga unos cambios

2021-10-05 02:06 UTC, afar-cmyk requested changes
Hola compañero, en cuanto a la lógica, me parece que esta muy bien, pero no podríamos implementar esta rama todavía, ya que se harán cambios sobre la estructura de los elementos y quizás eso implique tener que modificar tu trabajo, por el momento se cerrara, pero por favor no borrar la rama para no perder su trabajo, le recomiendo trabajar sobre otra rama y dejar estos ajustes intactos mientras encontramos una forma de como adicionarlos a la rama _main_.

2021-10-05 02:07 UTC, closed without merging