Index#69
afar-cmyk/ProyectoBibliotech pull request #79
Opened 2021-10-04 19:13 UTC by muakarada

Hola a todos, les comparto las anotaciones de la migración del sitio cliente y la adapatación a Bootstrap Vue:

1. Se adicionan las fuentes al index.html (**ojo revisar si concuerda**)
2. Cambios en los componentes NavBar.vue y Footer.vue para la adaptación
3. Cambios en style-index por lo realizado en los componentes (_ahora solo quedan ahí los estilos del navbar y footer_)
4. Se elimina de assets/images la imagen index-image
5. Se divide la imagen anterior y se suben index-image1 e index-image2 a assets/images como banner de home
6. Se completa migración de la vista trade.vue
7. Se completa migración de la vista team.vue
8. Se completa diseño responsive de home.vue
9. Se completa diseño responsive de trade.vue
10. Se completa diseño responsive de about.vue
11. Se completa diseño responsive de team.vue
12. Se añade: import vue modal a main.js **Ojo revisar sin concuerda**
13. Se elimina el logo de vue de assets
14. Se hacen cambios en los estilos de las vistas de acuerdo a la adaptación

https://user-images.githubusercontent.com/31747578/135910287-d2a761dc-bc7f-4cc8-806c-11315d647ba9.mp4

2021-10-04 19:15 UTC, Jesteban247 approved these changes

2021-10-05 01:58 UTC, jsstiven approved these changes
buen trabajo

2021-10-05 03:50 UTC, afar-cmyk requested changes
Se debe solucionar el problema con las dependencias de BootstrapVue al momento de desplegar el proyecto, se esta trabajando en una solución, por lo pronto se deja abierta la solicitud.

![image](https://user-images.githubusercontent.com/83623263/135957251-61e3c4cd-ad57-4576-b539-66605b2344fa.png)

2021-10-05 03:50 UTC, afar-cmyk commented on bibliotech/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@500;700;900&display=swap" rel="stylesheet">
Se reemplazaran las fuentes actuales del archivo index.html por las fuentes que estas declarando, eso lo haré en el momento que se acepte el commit, no se necesita ningun ajuste de tu parte.

2021-10-05 20:01 UTC, afar-cmyk commented on bibliotech/package-lock.json
> +  "name": "bibliotech",
Este cambio nunca supe si genera algun conflicto, pero si la instalación lo pone de esa forma, supongo que no hay ningun problema

2021-10-05 20:02 UTC, afar-cmyk submitted a review, later dismissed
Con los últimos cambios, al desplegar el servidor local en **Vue** compila bien y sin errores, se puede visualizar en escritorio y en dispositivos móviles sin ningún problema, muy buen trabajo compañera.

2021-10-05 20:23 UTC, jsstiven submitted a review, later dismissed

2021-10-05 20:48 UTC, lufermaxi commented
Se ve muy bien en dispositivo móvil el portal de usuario, gracias por tu trabajo Kelly!

2021-10-05 20:53 UTC, lufermaxi submitted a review, later dismissed
Se ve muy bien el portal de usuario en dispositivo móvil! gracias por tu trabajo Kelly.

2021-10-05 21:00 UTC, afar-cmyk approved these changes
Se han organizado los conflictos de la pagina **index.html**, se decidió quitar el enlace externo a el archivo _normalize.css_, se probaron las fuentes agregadas en otra rama y funciona bien, aunque deberán ser enlazadas en la vista **Login.vue** y en todas las vistas subsecuentes.

- Enlazar y declarar la fuente Roboto (Login.vue)

2021-10-05 21:19 UTC, lufermaxi approved these changes
Ok vista responsive.

2021-10-05 21:41 UTC, merged